//! RDPE - Reaction Diffusion Particle Engine
//!
//! GPU-accelerated particle simulations made easy.
//!
//! # Example
//! ```ignore
//! use rdpe::prelude::*;
//!
//! #[derive(Particle, Clone)]
//! struct MyParticle {
//!     position: Vec3,
//!     velocity: Vec3,
//! }
//!
//! fn main() {
//!     Simulation::<MyParticle>::new()
//!         .with_particle_count(10_000)
//!         .with_bounds(1.0)
//!         .with_spawner(|i, count| MyParticle {
//!             position: Vec3::ZERO,
//!             velocity: Vec3::new(0.0, 1.0, 0.0),
//!         })
//!         .with_rule(Rule::Gravity(9.8))
//!         .with_rule(Rule::BounceWalls)
//!         .run();
//! }
//! ```

mod gpu;
mod rules;
mod simulation;
mod spatial;

pub use bytemuck;
pub use glam::{Vec2, Vec3, Vec4};
pub use rdpe_derive::Particle;
pub use rules::Rule;
pub use simulation::Simulation;

/// The trait implemented by #[derive(Particle)]
///
/// This trait is automatically implemented by the derive macro.
/// Users should not implement this manually.
pub trait ParticleTrait: Clone + Send + Sync {
    /// The GPU-compatible representation of this particle.
    /// Generated automatically with proper padding for GPU memory layout.
    type Gpu: Copy + Clone + bytemuck::Pod + bytemuck::Zeroable + Send + Sync;

    /// WGSL struct definition generated by derive macro
    const WGSL_STRUCT: &'static str;

    /// Name of the field marked with #[color], if any
    const COLOR_FIELD: Option<&'static str>;

    /// Convert this particle to its GPU representation
    fn to_gpu(&self) -> Self::Gpu;
}

/// Prelude for convenient imports
pub mod prelude {
    pub use crate::rules::Rule;
    pub use crate::simulation::Simulation;
    pub use crate::ParticleTrait;
    pub use crate::{Vec2, Vec3, Vec4};
    pub use rdpe_derive::Particle;
}
